"""add_new_columns

Revision ID: 05056b759f3f
Revises: fe2009b2b700
Create Date: 2026-04-25 13:22:17.060310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '05056b759f3f'
down_revision: Union[str, Sequence[str], None] = 'fe2009b2b700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebase', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('knowledgebase', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('knowledgebase', sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('knowledgebase', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('knowledgebase', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('knowledgebase', 'file_name')
    op.add_column('ticket', sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ticket', sa.Column('admin_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_hash')
    op.drop_column('ticket', 'admin_response')
    op.drop_column('ticket', 'product_type')
    op.add_column('knowledgebase', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('knowledgebase', 'updated_at')
    op.drop_column('knowledgebase', 'created_at')
    op.drop_column('knowledgebase', 'product_type')
    op.drop_column('knowledgebase', 'category')
    op.drop_column('knowledgebase', 'title')
    # ### end Alembic commands ###
