"""add_is_escalation_to_ticket

Revision ID: 71ecbb21114d
Revises: ead8f9f62b0c
Create Date: 2026-05-08 00:09:06.706677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '71ecbb21114d'
down_revision: Union[str, Sequence[str], None] = 'ead8f9f62b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('is_escalation', sa.Boolean(), nullable=True))
    op.execute("UPDATE ticket SET is_escalation = true WHERE is_escalation IS NULL")
    op.alter_column('ticket', 'is_escalation', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'is_escalation')
    # ### end Alembic commands ###
