"""rename_product_type_to_division

Revision ID: a1b2c3d4e5f6
Revises: 05056b759f3f
Create Date: 2026-04-27 13:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '05056b759f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'product_type', new_column_name='division')
    op.alter_column('knowledgebase', 'product_type', new_column_name='division')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledgebase', 'division', new_column_name='product_type')
    op.alter_column('ticket', 'division', new_column_name='product_type')
    # ### end Alembic commands ###
