"""add_refresh_token_hash_to_user

Revision ID: fe2009b2b700
Revises: d6d61dcd0424
Create Date: 2026-04-23 17:12:04.349259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'fe2009b2b700'
down_revision: Union[str, Sequence[str], None] = 'd6d61dcd0424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_hash')
    # ### end Alembic commands ###
